class CreateJoinTableLanguagesInText < ActiveRecord::Migration[5.1]

  def change
    create_join_table :languages, :texts, {:table_name => 'other_text_languages'} do |t|
      t.index [:language_id, :text_id]
      t.index [:text_id, :language_id]
    end
    remove_index :languages, :ordinal
    add_index :languages, :ordinal

    iso_langs = [
        ['---','-----------',4],
        ['aar', 'Afar', 5],
        ['abk', 'Abkhazian', 5],
        ['afr', 'Afrikaans', 5],
        ['aka', 'Akan', 5],
        ['alb', 'Albanian', 5],
        ['amh', 'Amharic', 5],
        ['ara', 'Arabic', 5],
        ['arg', 'Aragonese', 5],
        ['arm', 'Armenian', 5],
        ['asm', 'Assamese', 5],
        ['ava', 'Avaric', 5],
        ['ave', 'Avestan', 5],
        ['aym', 'Aymara', 5],
        ['aze', 'Azerbaijani', 5],
        ['bak', 'Bashkir', 5],
        ['bam', 'Bambara', 5],
        ['baq', 'Basque', 5],
        ['bel', 'Belarusian', 5],
        ['ben', 'Bengali', 5],
        ['bih', 'Bihari languages', 5],
        ['bis', 'Bislama', 5],
        ['bos', 'Bosnian', 5],
        ['bre', 'Breton', 5],
        ['bul', 'Bulgarian', 5],
        ['bur', 'Burmese', 5],
        ['cat', 'Catalan', 5],
        ['cha', 'Chamorro', 5],
        ['che', 'Chechen', 5],
        ['chi', 'Chinese', 5],
        ['chu', 'Church Slavic', 5],
        ['chv', 'Chuvash', 5],
        ['cor', 'Cornish', 5],
        ['cos', 'Corsican', 5],
        ['cre', 'Cree', 5],
        ['cze', 'Czech', 5],
        ['dan', 'Danish', 5],
        ['div', 'Divehi', 5],
        ['dut', 'Dutch', 5],
        ['dzo', 'Dzongkha', 5],
        ['epo', 'Esperanto', 5],
        ['est', 'Estonian', 5],
        ['ewe', 'Ewe', 5],
        ['fao', 'Faroese', 5],
        ['fij', 'Fijian', 5],
        ['fin', 'Finnish', 5],
        ['fry', 'Western Frisian', 5],
        ['ful', 'Fulah', 5],
        ['geo', 'Georgian', 5],
        ['ger', 'German', 3],
        ['gla', 'Gaelic', 5],
        ['gle', 'Irish', 5],
        ['glg', 'Galician', 5],
        ['glv', 'Manx', 5],
        ['grn', 'Guarani', 5],
        ['guj', 'Gujarati', 5],
        ['hat', 'Haitian', 5],
        ['hau', 'Hausa', 5],
        ['heb', 'Hebrew', 5],
        ['her', 'Herero', 5],
        ['hin', 'Hindi', 5],
        ['hmo', 'Hiri Motu', 5],
        ['hrv', 'Croatian', 5],
        ['hun', 'Hungarian', 5],
        ['ibo', 'Igbo', 5],
        ['ice', 'Icelandic', 5],
        ['ido', 'Ido', 5],
        ['iii', 'Sichuan Yi', 5],
        ['iku', 'Inuktitut', 5],
        ['ile', 'Interlingue', 5],
        ['ina', 'Interlingua (International Auxiliary Language Association)', 5],
        ['ind', 'Indonesian', 5],
        ['ipk', 'Inupiaq', 5],
        ['ita', 'Italian', 3],
        ['jav', 'Javanese', 5],
        ['jpn', 'Japanese', 5],
        ['kal', 'Kalaallisut', 5],
        ['kan', 'Kannada', 5],
        ['kas', 'Kashmiri', 5],
        ['kau', 'Kanuri', 5],
        ['kaz', 'Kazakh', 5],
        ['khm', 'Central Khmer', 5],
        ['kik', 'Kikuyu', 5],
        ['kin', 'Kinyarwanda', 5],
        ['kir', 'Kirghiz', 5],
        ['kom', 'Komi', 5],
        ['kon', 'Kongo', 5],
        ['kor', 'Korean', 5],
        ['kua', 'Kuanyama', 5],
        ['kur', 'Kurdish', 5],
        ['lao', 'Lao', 5],
        ['lat', 'Latin', 5],
        ['lav', 'Latvian', 5],
        ['lim', 'Limburgan', 5],
        ['lin', 'Lingala', 5],
        ['lit', 'Lithuanian', 5],
        ['ltz', 'Luxembourgish', 5],
        ['lub', 'Luba-Katanga', 5],
        ['lug', 'Ganda', 5],
        ['mac', 'Macedonian', 5],
        ['mah', 'Marshallese', 5],
        ['mal', 'Malayalam', 5],
        ['mao', 'Maori', 5],
        ['mar', 'Marathi', 5],
        ['may', 'Malay', 5],
        ['mlg', 'Malagasy', 5],
        ['mlt', 'Maltese', 5],
        ['mon', 'Mongolian', 5],
        ['nau', 'Nauru', 5],
        ['nav', 'Navajo', 5],
        ['nbl', 'Ndebele, South', 5],
        ['nde', 'Ndebele, North', 5],
        ['ndo', 'Ndonga', 5],
        ['nep', 'Nepali', 5],
        ['nno', 'Norwegian Nynorsk', 5],
        ['nob', 'Bokmål, Norwegian', 5],
        ['nor', 'Norwegian', 5],
        ['nya', 'Chichewa', 5],
        ['oci', 'Occitan (post 1500)', 5],
        ['oji', 'Ojibwa', 5],
        ['ori', 'Oriya', 5],
        ['orm', 'Oromo', 5],
        ['oss', 'Ossetian', 5],
        ['pan', 'Panjabi', 5],
        ['per', 'Persian', 5],
        ['pli', 'Pali', 5],
        ['pol', 'Polish', 5],
        ['por', 'Portuguese', 5],
        ['pus', 'Pushto', 5],
        ['que', 'Quechua', 5],
        ['roh', 'Romansh', 5],
        ['rum', 'Romanian', 5],
        ['run', 'Rundi', 5],
        ['rus', 'Russian', 3],
        ['sag', 'Sango', 5],
        ['san', 'Sanskrit', 5],
        ['sin', 'Sinhala', 5],
        ['slo', 'Slovak', 5],
        ['slv', 'Slovenian', 5],
        ['sme', 'Northern Sami', 5],
        ['smo', 'Samoan', 5],
        ['sna', 'Shona', 5],
        ['snd', 'Sindhi', 5],
        ['som', 'Somali', 5],
        ['sot', 'Sotho, Southern', 5],
        ['spa', 'Spanish', 3],
        ['srd', 'Sardinian', 5],
        ['srp', 'Serbian', 5],
        ['ssw', 'Swati', 5],
        ['sun', 'Sundanese', 5],
        ['swa', 'Swahili', 5],
        ['swe', 'Swedish', 5],
        ['tah', 'Tahitian', 5],
        ['tam', 'Tamil', 5],
        ['tat', 'Tatar', 5],
        ['tel', 'Telugu', 5],
        ['tgk', 'Tajik', 5],
        ['tgl', 'Tagalog', 5],
        ['tha', 'Thai', 5],
        ['tib', 'Tibetan', 5],
        ['tir', 'Tigrinya', 5],
        ['ton', 'Tonga (Tonga Islands)', 5],
        ['tsn', 'Tswana', 5],
        ['tso', 'Tsonga', 5],
        ['tuk', 'Turkmen', 5],
        ['tur', 'Turkish', 3],
        ['twi', 'Twi', 5],
        ['uig', 'Uighur', 5],
        ['ukr', 'Ukrainian', 5],
        ['urd', 'Urdu', 5],
        ['uzb', 'Uzbek', 5],
        ['ven', 'Venda', 5],
        ['vie', 'Vietnamese', 5],
        ['vol', 'Volapük', 5],
        ['wel', 'Welsh', 5],
        ['wln', 'Walloon', 5],
        ['wol', 'Wolof', 5],
        ['xho', 'Xhosa', 5],
        ['yid', 'Yiddish', 5],
        ['yor', 'Yoruba', 5],
        ['zha', 'Zhuang', 5],
        ['zul', 'Zulu', 5],
    ]

    reversible do |direction|
      direction.up {add_all_languages iso_langs}
      direction.down {drop_added_languages iso_langs}
    end
  end

  def drop_added_languages(lang_list)
    for language in lang_list
      lang_to_del = Language.find_by code: language[0]
      lang_to_del.destroy
    end
  end

  def add_all_languages(lang_list)
    for language in lang_list
      new_lang = Language.new(name: language[1], code: language[0], ordinal: language[2])
      new_lang.save
    end
  end

end
